import json, re
from pathlib import Path
from xml.sax.saxutils import escape
ROOT=Path(__file__).resolve().parents[1]
langs=json.loads((ROOT/'lib/l10n/languages.json').read_text(encoding='utf-8'))
base=json.loads((ROOT/'lib/l10n/app_en.arb').read_text(encoding='utf-8'))
keys={k for k in base if not k.startswith('@')}
android=ROOT/'android/app/src/main/res'
entries=[]
for item in langs:
    code=item['code']
    path=ROOT/f'lib/l10n/app_{code}.arb'
    if not path.exists(): raise SystemExit(f'Missing catalog: {code}')
    catalog=json.loads(path.read_text(encoding='utf-8'))
    assert {k for k in catalog if not k.startswith('@')}==keys,code
    for key in keys:
        assert isinstance(catalog[key],str) and catalog[key].strip(),(code,key)
        assert set(re.findall(r'\{\w+\}',catalog[key]))==set(re.findall(r'\{\w+\}',base[key])),(code,key,'placeholders')
        assert not re.search(r'ZXQ|\[\[|\]\]|\n',catalog[key],re.I),(code,key,'translation marker')
    qualifier={'zh_Hant':'b+zh+Hant','he':'iw','id':'in','fil':'b+fil'}.get(code,code)
    folder=android/('values' if code=='en' else 'values-'+qualifier)
    folder.mkdir(parents=True,exist_ok=True)
    rows=[]
    for resource,key in [('mock_notification_title','mockActiveTitle'),('mock_notification_stop','stopMock'),('mock_notification_channel','notificationChannel')]:
        value=escape(catalog[key]).replace("'", "\\'").replace('"','\\"')
        rows.append(f'    <string name="{resource}">{value}</string>')
    (folder/'strings.xml').write_text('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tool/sync_l10n.py from ARB catalogs. -->\n<resources>\n'+'\n'.join(rows)+'\n</resources>\n',encoding='utf-8')
    locale="Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant')" if code=='zh_Hant' else f"Locale('{code}')"
    def dart(s): return "'"+s.replace('\\','\\\\').replace("'","\\'").replace('$','\\$')+"'"
    entries.append(f'  AppLanguage({locale}, {dart(item["english"])}, {dart(item["native"])}),')
source="""// Generated by tool/sync_l10n.py. Edit languages.json instead.
import 'package:flutter/widgets.dart';

class AppLanguage {
  final Locale locale;
  final String englishName;
  final String nativeName;
  const AppLanguage(this.locale, this.englishName, this.nativeName);
}

const appLanguages = <AppLanguage>[
"""+'\n'.join(entries)+'\n];\n'
(ROOT/'lib/l10n/languages.dart').write_text(source,encoding='utf-8')
print(f'Validated {len(langs)} catalogs x {len(keys)} messages; synchronized Android notification strings and language list.')

native = ROOT/'android/app/src/main/kotlin/com/deploydulupulangnanti/fake_gps_pro/AppLanguageCodes.kt'
native.write_text('// Generated by tool/sync_l10n.py.\npackage com.deploydulupulangnanti.fake_gps_pro\n\nobject AppLanguageCodes {\n    val supported = setOf(\n        '+', '.join('"'+x['code'].split('_')[0]+'"' for x in langs if x['code']!='zh_Hant')+'\n    )\n}\n',encoding='utf-8')
